### ISSUE TITLE
All cells have an area of X km2? Fill the blank

### ISSUE THREAD

**Issue by Matt-Navarro** [UWA-Marine-Ecology-Group-projects/DBCA-marine-park-planning#24]

**Comment by BrookeGibbons** [comment]
Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  4.705   4.727   4.736   4.754   4.780   4.855

**Comment by BrookeGibbons** [comment]
I'm going to put it as ~2.5 km across at the widest point and an area of ~4.75 km2
